### PR TITLE
Docs migration

### PR DESCRIPTION
**Pull request by lovincyrus**
Live: https://cosmwasm-docs.netlify.app

### Next steps:
- [ ] replace the logo.svg in `docs/.vuepress/public`
- [x] update the frontmatter in each md files https://github.com/CosmWasm/docs/pull/47/commits/9e5442999b9839f43ca16acf033872b843d46f7c
  - [x] updated the frontmatter of `/intro`
- [x] syntax highlighting for `rust` https://github.com/tendermint/cosmos-ui/pull/201

### CODE REVIEW

**Comment by ethanfrey** [comment]
I took a look and the design is quite nice. I am happy to wait until next week when the theme is properly published and then we can move over the docs.

One issue I found is the left sidebar.
Look at https://cosmwasm-docs.netlify.app/getting-started/first-demo.html
vs https://www.cosmwasm.com/docs/getting-started/first-demo

[This file contains the ordering of pages]((https://github.com/CosmWasm/docs/blob/master/website/sidebars.json) within each section (note that one page is hidden and just linked from another - solutions on how to solve if you are stuck)

I'm sure there is a way to do that with the vuepress theme. Otherwise, :rocket: :guitar: :rabbit:

**Comment by ethanfrey** [comment]
I also noticed the syntax highlighting on the code is gone. I think this all comes from [highlight.js](https://highlightjs.org/) under the hood. It would be cool if vuepress also supported this (as I will have quite some code samples)

**Comment by lovincyrus** [comment]
> One issue I found is the left sidebar.
> Look at https://cosmwasm-docs.netlify.app/getting-started/first-demo.html
> vs https://www.cosmwasm.com/docs/getting-started/first-demo
> 
> [This file contains the ordering of pages]((https://github.com/CosmWasm/docs/blob/master/website/sidebars.json) within each section (note that one page is hidden and just linked from another - solutions on how to solve if you are stuck)

Gotcha - I've only updated the `/intro` page so far. ~~You may update the rest by tweaking [the `order: 1` in each .md file](https://github.com/CosmWasm/docs/pull/47/files#diff-a62e47f56c367e27bbaf8b4cfb383969R3).~~ (fixed)

**Comment by lovincyrus** [comment]
> I also noticed the syntax highlighting on the code is gone. I think this all comes from [highlight.js](https://highlightjs.org/) under the hood. It would be cool if vuepress also supported this (as I will have quite some code samples)

VuePress is currently using [Prism](https://prismjs.com) for its syntax highlighting. I'll take a look at why it's not working for the `rust` code.

Reference: https://vuepress.vuejs.org/guide/markdown.html#syntax-highlighting-in-code-blocks

**Comment by ethanfrey** [comment]
> VuePress is currently using Prism for its syntax highlighting. I'll take a look at why it's not working for the rust code.

Odd, Rust support seems to be present in Prism.js for years... https://github.com/PrismJS/prism/pull/430

I did notice the examples seemed to start with "``` language" rather than "```language", maybe the space is necessary?

**Comment by lovincyrus** [comment]
> Odd, Rust support seems to be present in Prism.js for years... [PrismJS/prism#430](https://github.com/PrismJS/prism/pull/430)

The syntax highlighting for `rust` should be fixed in this PR https://github.com/tendermint/cosmos-ui/pull/201/files#diff-0067b8cefd607df5bea9785b2a502e69R404

**Comment by ethanfrey** [comment]
This still needs an updated logo, right (we are working on it).
Otherwise, from your end, this is ready to go?

**Comment by ethanfrey** [comment]
I guess the netlify docs are not updated yet with the rust patch?

https://cosmwasm-docs.netlify.app/getting-started/editing-escrow-contract.html

When this is all ready, I am happy to merge and deploy tomorrow or next week.
We should have a logo in a week or two as well :crossed_fingers:

**Comment by lovincyrus** [comment]
> I guess the netlify docs are not updated yet with the rust patch?
> 
> https://cosmwasm-docs.netlify.app/getting-started/editing-escrow-contract.html

Just deployed the latest version to Netlify! 🚀

**Comment by lovincyrus** [comment]
> This still needs an updated logo, right (we are working on it).
> Otherwise, from your end, this is ready to go?

Yes!

**Comment by ethanfrey** [comment]
> Just deployed the latest version to Netlify! :rocket:

Great. I checked it out and it looks much nicer. Not quite as good as my IDE :wink: but nice highlighting.
Logo should come in 1-2 weeks.

Is there a README on how to deploy? It seems only the docs dir matters now (we will pull out the website into a separate place - actually static rather than docs homepage).  I guess this is how I would deploy it?

```
cd docs
yarn install
yarn build
// then deploy the build scripts somewhere??
```

And this seems like the proper docs to set up github pages (or other) deployment: https://vuepress.vuejs.org/guide/deploy.html#github-pages correct?

I will dig into this next week to make it live. Thank you for the help.

**Comment by lovincyrus** [comment]
> Is there a README on how to deploy? It seems only the docs dir matters now (we will pull out the website into a separate place - actually static rather than docs homepage). I guess this is how I would deploy it?
> 
> ```
> cd docs
> yarn install
> yarn build
> // then deploy the build scripts somewhere??
> ```
> 
> And this seems like the proper docs to set up github pages (or other) deployment: https://vuepress.vuejs.org/guide/deploy.html#github-pages correct?

I wrote up a [DOCS_README](https://github.com/CosmWasm/docs/blob/e94ff87e07715b373a2cf22c117114489565b5ab/docs/DOCS_README.md). But, that's the gist of it. You just need to use a deployment service of your choice and deploy the dir in `docs/.vuepress/dist`. 

**Example**:
https://default-docs.netlify.app/
image

You can refer to https://default-docs.netlify.app/basic/03-used-by.html for more examples.

**Review by ethanfrey — APPROVED** [review]
Great, I will merge and work on deployment from my end

**Pull request merged**
