### PR TITLE
Update first-demo.md

### PR DESCRIPTION
**Pull request by okwme**
So cooool

### CODE REVIEW

**Comment by okwme** [comment]
I noticed something weird tho:
```
> wasmcli query account $(wasmcli keys show thief -a)

{
  "type": "cosmos-sdk/Account",
  "value": {
    "address": "cosmos1el2cc9zgw6jtsr0ny08m4f6seqze6y9gxljgkx",
    "coins": [
      {
        "denom": "stake",
        "amount": "30001"
      }
    ],
    "public_key": "cosmospub1addwnpepqvetsmp4py8d2fp3uczhj3gkmfryxjtg8nw2st3mtrgd6735268y6jzukq0",
    "account_number": 8,
    "sequence": 1
  }
}
```
Why does the thief have 30001 stake? 
Previously the contract only had 30000:
```
wasmcli query account $CONTRACT

{
  "type": "cosmos-sdk/Account",
  "value": {
    "address": "cosmos18vd8fpwxzck93qlwghaj6arh4p7c5n89uzcee5",
    "coins": [
      {
        "denom": "stake",
        "amount": "30000"
      }
    ],
    "public_key": "",
    "account_number": 9,
    "sequence": 0
  }
}
```
and bob had 20000
```
 wasmcli query account $(wasmcli keys show bob -a)

{
  "type": "cosmos-sdk/Account",
  "value": {
    "address": "cosmos1d3jhdvg9ccvu9aa2dylp74qr2tywga7a38rwa6",
    "coins": [
      {
        "denom": "stake",
        "amount": "20000"
      }
    ],
    "public_key": "",
    "account_number": 10,
    "sequence": 0
  }
}
```

**Comment by ethanfrey** [comment]
In the beginning you give the thief 1 stake, so he can execute the "steal tx". Cosmos SDK doesn't allow accounts to sign messages unless they exist (which means they have a balance, or at least HAD a balance). In production, he would need some minimal amount to pay gas.

I will add a note.

**Review by ethanfrey — APPROVED** [review]
Nice additions, I will add comments to explain the final balances. Thanks for running this all the way through.

**Comment by okwme** [comment]
oh jaaaa, now i remember : )
:+1:

**Pull request merged**
